import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>
            Imminent - The most spectacular coming soon template!
        </title>
        <meta content="yes" name="mobile-web-app-capable" />
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport" />
        <meta content="ThemeWagon" name="author" />
        <meta content="The most spectacular coming soon template!" name="description" />
        <meta content="Comming Soon, Responsive, Landing Page, One Page" name="keywords" />
        <meta content="The most spectacular coming soon template!" />
        <meta content="ThemeWagon" />
        <meta content="ThemeWagon" />
        <meta content="website" />
        <meta content="index.html" />
        <meta content="summary" name="twitter:card" />
        <meta content="@themewagon" name="twitter:site" />
        <meta content="@themewagon" name="twitter:creator" />
        <meta content="ThemeWagon" name="twitter:title" />
        <meta content="Imminent - The most spectacular coming soon template!" name="twitter:description" />

        <link href="favicon.png" rel="shortcut icon" type="image/png" />

        <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,900' rel='stylesheet' type='text/css' />
        <link href="css/loader.css" rel="stylesheet" type="text/css" />
        <link href="css/normalize.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="css/font-awesome.min.css" />
        <link href="css/style.css" rel="stylesheet" type="text/css" />
        <script src="js/jquery.js"></script>
    </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
